language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements_build.txt
  - psql -c 'create database travis_ci_test;' -U postgres

env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

services:
  - postgresql
 
script:
  - ./Pur-Beurre/manage.py test


